version: '3.7'
volumes:
  prometheus-data: {}
  grafana_data: {}
networks:
  plekhanovsa-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: plekhanovsa-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - plekhanovsa-my-netology-hw
    restart: always
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: plekhanovsa-netology-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - plekhanovsa-my-netology-hw
    restart: always
    deploy:
      mode: global
  pushgateway:
    image: prom/pushgateway
    container_name: plekhanovsa-netology-pushgateway
    depends_on:
      - prometheus
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - plekhanovsa-my-netology-hw
  grafana:
    image: grafana/grafana
    container_name: plekhanovsa-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    ports:
      - 8080:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana
      - ./custom.ini:/etc/grafana/grafana.ini
    networks:
      - plekhanovsa-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped
  alertmanager:
    image: prom/alertmanager
    container_name: plekhanovsa-netology-alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - plekhanovsa-my-netology-hw
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
